# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Portfolio' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  
  use_frameworks!
  pod 'TextFieldEffects', '~> 1.5'

  # Pods for Portfolio

end
